version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  # TODO: We should remove this file and decouple the infra from CircleCI once we've proven GitHub Actions is working
  build_and_test:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test --watchAll=false
          name: Run tests

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
